---
title: "about_ssm"
output: html_document
---

### How do we measure stream health?

Bacteria concentration of water samples can act as an indicator for the presence of sewage, which may contain harmful pathogens that pose a risk to human health. However, bacteria concentrations can also be elevated due storm events or other factors. To have get a clear picture of stream quality, it is important to look at patterns over time.

In this dashboard we use the **percent of times a site exceeded the single sample maximum** in a year. The **single sample maximum** is an upper limit threshold value used in environmental and public health monitoring. If any single test sample crosses this specific concentration limit, it can indicate harmful bacteria levels in the water.

The two indicator bacteria used are *Escherichia coli* (E. coli) (for freshwater sites) and *Enterococci* (Enetero) for estuarine sites. This dashboard uses the  CT DEEP geometric mean criterion (< 126 MPN/100 mL for freshwater sites or < 35 MPN/100 mL for estuarine sites) as the single sample threshold.
